 nginx:
   build: nginx
   volumes:
    - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
    - "./src/public_html:/var/www"
   ports:
    - "8080:80"
   environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
   command: nginx -g "daemon off;"
   links:
    - php-fpm

 php-fpm:
  build: php
 mysql:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
   - "3306:3306"
  volumes:
   - "./php:/home/docker:rw"
   - "./src/public_html:/var/www"
  environment:
   MYSQL_ROOT_PASSWORD: root_test
